#!/bin/bash

if [[ ${HEADLESS} == 'yes' || ${HEADLESS} == '1' ]]; then
  exec chromium --headless --no-sandbox --disable-dev-shm-usage --disable-gpu --window-size=${WINDOWSIZE//x/,} "$@"
else
  if [[ -z $(pidof Xvfb) ]]; then
    Xvfb :0 -screen 0 ${WINDOWSIZE//,/x}x24 > /tmp/xvfb.log 2>&1 &
    sleep 2
  fi
  export DISPLAY=:0.0
#  exec xvfb-run --server-args="-screen 0 ${WINDOWSIZE//,/x}x24" \
  exec chromium --no-sandbox --disable-dev-shm-usage --disable-gpu --window-size=${WINDOWSIZE//x/,} "$@"
fi