#!/bin/bash
###################################################################
# 'Wrapper' to easily run RF tests in a container
# Example: sh testcontainer robotlooper -t "my test" testsuites
###################################################################
# Verify first cli argument is correct
if [ $1 != 'robot' ] && [ $1 != 'robotlooper' ] && [ $1 != 'rebot' ]; then
    echo "Please choose between 'robot', 'robotlooper' or 'rebot' as exec command"
    exit 1
fi
# Set runner (since robotlooper is a bash script file, small workaround solution.)
if [ $1 == 'robotlooper' ]; then
    runner="sh robotlooper"
else
    runner=$1
fi
# can be run from root of project or root of test folder
CURDIR=$(pwd | grep -o '[^/]*$')
if [ $CURDIR = 'test' ]; then
    docker-compose -f ./../docker-compose-test.yml run --rm test $runner "${@:2}"
elif [ $CURDIR = 'fullStackFit' ]; then
    docker-compose -f docker-compose-test.yml run --rm test $runner "${@:2}"
else
    echo "Please run this script from ./test or ./fullStackfit (root)"
    exit 1
fi