# base image
FROM node:12.2.0

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# No need to npm install because the host node_modules folder is mounted inside the Docker container
RUN npm install -g @angular/cli 

# Not needed because in Dev we mount the host project folder to the container
# COPY . /app

# start app
CMD ng serve --host 0.0.0.0 --live-reload true

# Build
# docker image build -f Dockerfile-dev -t frontend:dev .

# Run
# docker run --rm --name frontend -v ${PWD}:/app -p 4200:4200 frontend:dev