# steps:
# - name: 'docker/compose:1.15.0'
#   args: ['-f', 'docker-compose-prod.yml', 'up', '-d']
#   tags: ['cloud-builders-community']
# # - name: 'gcr.io/cloud-builders/docker'
# #   args: ['tag', fit_reverseproxy-prod:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
# # Push the container image to Container Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/$PROJECT_ID/fullstackfit_backend:latest']
#images: ['gcr.io/$PROJECT_ID/fullstackfit_backend:latest', 'gcr.io/$PROJECT_ID/fullstackfit_backend:latest', 'gcr.io/$PROJECT_ID/fullstackfit_reverseproxy:latest']
# images:
# - gcr.io/$PROJECT_ID/fullstackfit:latest

# steps:
# # Build the container image
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/[PROJECT_ID]/[IMAGE]', '.']
# # Push the container image to Container Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/[PROJECT_ID]/[IMAGE]']
# # Deploy container image to Cloud Run
# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['run', 'deploy', '[SERVICE_NAME]', '--image', 'gcr.io/[PROJECT_ID]/[IMAGE]', '--region', '[REGION]', '--platform', 'managed', '--allow-unauthenticated']
# images:
# - gcr.io/[PROJECT_ID]/[IMAGE]


# https://cloud.google.com/cloud-build/docs/deploying-builds/deploy-cloud-run

#cloudbuild.yaml
steps:
- name: 'docker/compose:1.19.0'
  args: ['-f', 'docker-compose-prod.yml', 'up', '-d']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_app:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']