steps:
- name: 'docker/compose:1.15.0'
  args: ['-f', 'docker-compose-prod.yml', 'up', '-d']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_app:latest', 'gcr.io/$PROJECT_ID/fullstackfit:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/fullstackfit:$COMMIT_SHA']