version: '3.3'
services:
  
  reverseproxy:
    container_name: fit_reverseproxy-b
    ports:
      - 80:80
    restart: always
    image: "fullstackfit_reverseproxy:dev"
    build:
      context: ./reverse-proxy
    volumes:
     - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
      - iam
      - database

  frontend:
    container_name: fit_frontend-dev
    image: fullstackfit_frontend:dev
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    volumes:
      - './frontend:/app'
    ports:
     - 4200:4200
    # depends_on: 
    #   - database
    #   - backend
    
  backend:
    container_name: fit_backend-b
    image: "fullstackfit_backend:dev"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - iam
      - database
  
  iam:
    container_name: fit_iam-b
    image: "fullstackfit_iam:dev"
    build:
      context: ./iam
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
      - DB_VENDOR=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_ADDR=database
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_SCHEMA=iam
      # - KEYCLOAK_FRONTEND_URL=http://localhost/auth
    depends_on:
      - database

  database:
    container_name: fit_database-b
    image: "fullstackfit_database:dev"
    build:
      context: ./database
      dockerfile: Dockerfile 
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
  
volumes:
  data: