version: '3.3'
services:

  ######################################################################
  # This compose file builds Release Candidate (rc) images
  # tagged with the environment variable GIT_COMMIT_SHA.
  # This is the ID of the CI worklfow.
  ######################################################################
  
  reverseproxy:
    container_name: fit_reverseproxy-b
    ports:
      - 80:80
    restart: always
    image: "fullstackfit_reverseproxy:b.${IMAGE_TAG}"
    build:
      context: ./reverse-proxy
    depends_on:
      - database
      - backend
      - frontend

  frontend:
    container_name: fit_frontend-b
    image: "fullstackfit_frontend:b.${IMAGE_TAG}"
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
      - 'config=production'
    environment:
      - PORT=4200
    depends_on:
      - database
      - backend
    
  backend:
    container_name: fit_backend-b
    image: "fullstackfit_backend:b.${IMAGE_TAG}"
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
  
  database:
    container_name: fit_database-b
    image: "fullstackfit_database:b.${IMAGE_TAG}"
    build:
      context: ./database
      dockerfile: Dockerfile 
    ports:
      - 5432:5432