version: '3.3'
services:

  ######################################################################
  # This compose file runs the containers with hot reloading enabled
  # and mapping the ports of the specific services to the host
  ######################################################################

  reverseproxy:
    container_name: fit_reverseproxy-dev
    image: fullstackfit_reverseproxy:dev
    depends_on:
      - database
      - frontend
      - backend
    ports:
      - 80:80
    restart: always
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    # Use ./reverseproxy/fswatch.sh for hot reloading nginx in the Docker container.
    volumes:
      - './reverse-proxy/nginx.conf:/etc/nginx/nginx.conf'

  frontend:
    container_name: fit_frontend-dev
    image: bamaas/fullstackfit_frontend:dev
    depends_on: 
      - database
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    volumes:
      - './frontend:/app'
    # Mapping to host for dev purpose.
    ports:
     - 4200:4200

  backend:
    container_name: fit_backend-dev
    image: fullstackfit_backend:dev
    restart: always
    depends_on: 
      - database
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/src'
    environment:
      - RELOAD=True
      - PORT=5000
    # Mapping to host for dev purpose.
    ports:
      - 5000:5000

  database:
    container_name: fit_database-dev
    image: fullstackfit_database:dev
    build:
      context: ./database
      dockerfile: Dockerfile
    # This will make the data persistent  
    # volumes:
    #   - '${PWD}/volumes/database:/var/lib/postgresql/data'
    # Not possible to move the database.env file to the /database folder because its a seperate container
    env_file: './backend/database.env'
    # Mapping to host for dev purpose.
    ports:
      - 5432:5432