version: '3.3'
services:

  # https://blog.pusher.com/full-stack-testing-docker-compose/
  test:
    container_name: fit_test
    build:
      context: ./test
      dockerfile: Dockerfile
    volumes:
      - './test:/src'
    network_mode: host
    command: -d logs testsuites