version: '3.3'
services:

  ######################################################################
  # This compose file builds Release Candidate (rc) images
  # tagged with the environment variable GIT_COMMIT_SHA.
  # This is the ID of the CI worklfow.
  ######################################################################
  
  reverseproxy:
    container_name: fit_reverseproxy-b
    ports:
      - 80:80
    restart: always
    image: "fullstackfit_reverseproxy:b.${IMAGE_TAG}"
    build:
      context: ./reverse-proxy
    volumes:
     - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
      - iam
      - database

  frontend:
    container_name: fit_frontend-b
    image: "fullstackfit_frontend:b.${IMAGE_TAG}"
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
      - 'config=production'
    environment:
      - PORT=4200
    ports:
      - 4200:4200
    depends_on:
      - backend
      - iam
      - database
    
  backend:
    container_name: fit_backend-b
    image: "fullstackfit_backend:b.${IMAGE_TAG}"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - iam
      - database
  
  iam:
    container_name: fit_iam-b
    image: "fullstackfit_iam:b.${IMAGE_TAG}"
    build:
      context: ./iam
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
      - DB_VENDOR=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_ADDR=database
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_SCHEMA=iam
      - KEYCLOAK_FRONTEND_URL=http://localhost/auth
    depends_on:
      - database

  database:
    container_name: fit_database-b
    image: "fullstackfit_database:b.${IMAGE_TAG}"
    build:
      context: ./database
      dockerfile: Dockerfile 
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
  
volumes:
  data: