version: '3.3'
services:

  # With the use of this reverse proxy both the frontend and backend are accessable through port 80.
  # In this way I expose an public api
  # Backend adress: baseURL/api/
  reverseproxy:
    container_name: fit_reverseproxy-prod
    ports:
      - 80:80
    restart: always
    image: fullstackfit_reverseproxy:latest
    build:
      context: ./reverse-proxy

  frontend:
    container_name: fit_frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
      - 'config=production'
    environment:
      - PORT=4200
    
  backend:
    container_name: fit_backend-prod
    image: fullstackfit_backend:latest
    restart: always
    depends_on: 
      - reverseproxy
      - database
    environment:
      - RELOAD=False
      - PORT=5000
    build:
      context: ./backend
      dockerfile: Dockerfile

  database:
    container_name: fit_database-prod
    depends_on:
     - reverseproxy
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file: './backend/database.env'    
    ports:
      - 5432:5432