version: '3.3'
services:

  test:
    container_name: fullstackfit_test
    image: bamaas/fullstackfit_test:latest
    build:
      context: ./test
      dockerfile: Dockerfile
    volumes:
      - './test:/src'
    network_mode: host
    env_file:
      - './test/.env'
    command: -d logs testsuites