pull_request_rules:
  - name: Automatic merge on checks passed ✔
    conditions:
      - label=auto-pr
      - "status-success=ci/semaphoreci/push: lint, build and test"
      - base=master
    actions:
      merge:
        method: squash
        commit_message: default
        rebase_fallback: merge
        strict: true
        strict_method: "smart+fasttrack"