pull_request_rules:
  - name: Automatic merge on checks passed ✔
    conditions:
      - label=auto-pr
      - "status-success=ci/semaphoreci/push: Build & Test"
      - base=master
    actions:
      merge:
        method: merge
        strict: true