pull_request_rules:
  - name: Automatic merge on checks passed ✔
    conditions:
      - label=auto-pr
      - "ci/semaphoreci/push: lint, build and test"
      - base=master
    actions:
      merge:
        method: merge
        strict: true