FROM tiangolo/uwsgi-nginx-flask:python3.7

COPY requirements.txt /app
RUN pip install --upgrade pip \
    && pip install -r ./requirements.txt

ENV LISTEN_PORT 5000

EXPOSE 5000

COPY ./app /app

# BUILD
# docker build -f Dockerfile-prod -t myprodimg .

# RUN
# docker run --rm --name mycontainer -p 5000:5000 myprodimg

# DOCUMENTATION
# https://github.com/tiangolo/uwsgi-nginx-flask-docker