FROM python:3.7.4-stretch

WORKDIR /src

# First install the dependencies. Docker will skip the RUN part if it detects that there are no changes on the COPY part
COPY requirements.txt /src
RUN pip install --upgrade pip \
    && pip install -r ./requirements.txt

# Not needed because in Dev we mount the host project folder to the container
# COPY ./app /src

CMD ["python", "./app/main.py"]

## Running via command line (from current working dir):
# docker run -p 5000:5000 -v ${PWD}:/src --rm --name backend backend:latest python app.py