pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t backend .'
            }
        }
        stage('Test') {
            steps {
                sh 'sh docker run --rm --name backend-test backend:latest python tests.py'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker run --rm --name backend -d -p 80:5000 backend:latest'
            }
        }
    }
}