version: '3.7'
services:

  database:
    container_name: fit_database
    build:
      context: ./database
      dockerfile: Dockerfile
    # This will make the data persistent  
    # volumes:
    #   - '${PWD}/volumes/database:/var/lib/postgresql/data'
    env_file: './backend/database.env'
    ports:
      - 5432:5432