apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: backend
  name: backend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: bamaas/fullstackfit_backend:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 25
          periodSeconds: 2
          successThreshold: 1
          tcpSocket:
            port: 5000
          timeoutSeconds: 2
        name: backend
        ports:
        - containerPort: 5000
          name: backendport
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 25
          periodSeconds: 2
          successThreshold: 2
          tcpSocket:
            port: 5000
          timeoutSeconds: 2
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      initContainers:
      - name: liquibase
        image: bamaas/fullstackfit_liquibase:latest
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
