apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: backend
  name: backend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: bamaas/fullstackfit_backend:latest
        env:
        - name: KEYCLOAK_AUTH_SERVER_URL
          value: http://iam:8080/auth
        - name: DATABASE_HOST
          value: "database"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_DB
          value: postgres
        - name: DATABASE_USERNAME
          value: postgres
        - name: DATABASE_PASSWORD
          value: postgres
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 4
          initialDelaySeconds: 53
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 5000
          timeoutSeconds: 3
        resources:
          requests:
            memory: "300Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
          name: backendport
          protocol: TCP
        readinessProbe:
          failureThreshold: 4
          initialDelaySeconds: 53
          periodSeconds: 5
          successThreshold: 2
          tcpSocket:
            port: 5000
          timeoutSeconds: 3
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      initContainers:
      - name: liquibase
        image: bamaas/fullstackfit_liquibase:latest
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
