apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: frontend
  name: frontend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - env:
        - name: PORT
          value: "4200"
        image: bamaas/fullstackfit_frontend:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 4200
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        name: frontend
        ports:
        - containerPort: 4200
          name: 4200tcp327341
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 4200
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      resources:
        requests:
          memory: "5Mi"
          cpu: "5m"
        limits:
          memory: "50Mi"
          cpu: "10m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30