apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: landing
  name: landing
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: landing
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: landing
    spec:
      containers:
      - image: bamaas/fullstackfit_landing:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 2
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 2
        name: landing
        resources:
          requests:
            memory: "5Mi"
            cpu: "5m"
          limits:
            memory: "50Mi"
            cpu: "10m"
        ports:
        - containerPort: 80
          name: landing80tcp
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 2
          successThreshold: 2
          tcpSocket:
            port: 80
          timeoutSeconds: 2
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
