apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
spec:
  ports:
  - name: 80tcp-proxy
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: reverse-proxy
  sessionAffinity: None
  type: ClusterIP