version: v1.0
name: Build & Test
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Checkout
    skip:
      when: "branch != 'dev'"
    task:
      jobs:
        - name: linter
          commands: 
            - pip install flake8
            - echo linting...
        - name: unit tests
          commands: 
            - make test-unit
      prologue:
        commands:
          - checkout
          - sem-version python 3.7
  - name: Build
    skip:
      when: "branch != 'dev'"
    task:
      jobs:
        - name: database
          commands:
            - make build-db
            - docker tag fullstackfit_database:b.${GIT_COMMIT_SHA} ${DOCKER_USERNAME}/registry:fullstackfit_database.${GIT_COMMIT_SHA}
            - docker push ${DOCKER_USERNAME}/registry:fullstackfit_database.${GIT_COMMIT_SHA}
        - name: backend
          commands:
            - make build-be
            - docker tag fullstackfit_backend:b.${GIT_COMMIT_SHA} ${DOCKER_USERNAME}/registry:fullstackfit_backend.${GIT_COMMIT_SHA}
            - docker push ${DOCKER_USERNAME}/registry:fullstackfit_backend.${GIT_COMMIT_SHA}
        - name: frontend
          commands:
            - make build-fe
            - docker tag fullstackfit_frontend:b.${GIT_COMMIT_SHA} ${DOCKER_USERNAME}/registry:fullstackfit_frontend.${GIT_COMMIT_SHA}
            - docker push ${DOCKER_USERNAME}/registry:fullstackfit_frontend.${GIT_COMMIT_SHA}
        - name: proxy
          commands:
            - make build-proxy
            - docker tag fullstackfit_reverseproxy:b.${GIT_COMMIT_SHA} ${DOCKER_USERNAME}/registry:fullstackfit_reverseproxy.${GIT_COMMIT_SHA}
            - docker push ${DOCKER_USERNAME}/registry:fullstackfit_reverseproxy.${GIT_COMMIT_SHA}
      prologue:
        commands:
          - checkout
          - export GIT_COMMIT_SHA=$(git rev-parse --short HEAD)
          - echo $GIT_COMMIT_SHA
          - echo $DOCKER_PASSWORD | docker login --username "$DOCKER_USERNAME" --password-stdin
      secrets:
        - name: docker
  - name: Test
    skip:
      when: "branch != 'dev'"
    task:
      jobs:
        - name: api
          commands:
            - sh testbot -v environment:localhost testsuites/ws.robot
        - name: e2e
          commands:
            - sh testbot -v environment:localhost testsuites/gui.robot
      prologue:
        commands:
          - checkout
          - export GIT_COMMIT_SHA=$(git rev-parse --short HEAD)
          - echo $GIT_COMMIT_SHA
          - echo $DOCKER_PASSWORD | docker login --username "$DOCKER_USERNAME" --password-stdin
          # Pull images from bamaas/registry (private container registry)
          - echo ${DOCKER_USERNAME}/registry:fullstackfit_frontend.${GIT_COMMIT_SHA} ${DOCKER_USERNAME}/registry:fullstackfit_backend.${GIT_COMMIT_SHA} ${DOCKER_USERNAME}/registry:fullstackfit_reverseproxy.${GIT_COMMIT_SHA} ${DOCKER_USERNAME}/registry:fullstackfit_database.${GIT_COMMIT_SHA} | xargs -n 1 docker pull
          # Retag to latest
          - echo $DOCKER_USERNAME/registry:fullstackfit_frontend.$GIT_COMMIT_SHA $DOCKER_USERNAME/fullstackfit_frontend:latest $DOCKER_USERNAME/registry:fullstackfit_backend.$GIT_COMMIT_SHA $DOCKER_USERNAME/fullstackfit_backend:latest $DOCKER_USERNAME/registry:fullstackfit_database.$GIT_COMMIT_SHA $DOCKER_USERNAME/fullstackfit_database:latest $DOCKER_USERNAME/registry:fullstackfit_reverseproxy.$GIT_COMMIT_SHA $DOCKER_USERNAME/fullstackfit_reverseproxy:latest | xargs -n 2 docker tag
          # Start application with make latest. In This way we start the application the same was as in production
          - make latest
      epilogue:
        always:
          commands:
            - make shutdown
            - artifact push job ./test/logs/log.html
        on_pass:
          commands:
            # Tag & Push :$GIT_COMMIT_SHA to public Docker Hub of the corresponding image
            # By doing this we gather all the passed builds in the public Docker Hub repository corresponding with the Git commit sha
            - echo $DOCKER_USERNAME/registry:fullstackfit_frontend.$GIT_COMMIT_SHA $DOCKER_USERNAME/fullstackfit_frontend:$GIT_COMMIT_SHA $DOCKER_USERNAME/registry:fullstackfit_backend.$GIT_COMMIT_SHA $DOCKER_USERNAME/fullstackfit_backend:$GIT_COMMIT_SHA $DOCKER_USERNAME/registry:fullstackfit_database.$GIT_COMMIT_SHA $DOCKER_USERNAME/fullstackfit_database:$GIT_COMMIT_SHA $DOCKER_USERNAME/registry:fullstackfit_reverseproxy.$GIT_COMMIT_SHA $DOCKER_USERNAME/fullstackfit_reverseproxy:$GIT_COMMIT_SHA | xargs -n 2 docker tag
            - echo ${DOCKER_USERNAME}/fullstackfit_frontend:$GIT_COMMIT_SHA ${DOCKER_USERNAME}/fullstackfit_backend:$GIT_COMMIT_SHA ${DOCKER_USERNAME}/fullstackfit_reverseproxy:$GIT_COMMIT_SHA ${DOCKER_USERNAME}/fullstackfit_database:$GIT_COMMIT_SHA | xargs -n 1 docker push
            # Push :latest to Docker Hub
            - echo ${DOCKER_USERNAME}/fullstackfit_frontend:latest ${DOCKER_USERNAME}/fullstackfit_backend:latest ${DOCKER_USERNAME}/fullstackfit_reverseproxy:latest ${DOCKER_USERNAME}/fullstackfit_database:latest | xargs -n 1 docker push
      secrets:
        - name: docker
  - name: Merge
    skip:
      when: "branch != 'dev'"
  # On successful build -> merge from the dev (trunk) branch to prod and release it.
    task:
      jobs:
        - name: to prod
          commands:
          - git fetch
          - git checkout -b prod
          - git push -q https://$GITHUB_TOKEN@github.com/bamaas/FullStackFit.git prod
      prologue:
        commands:
          - checkout
          - export GIT_COMMIT_SHA=$(git rev-parse --short HEAD)
          - echo $GIT_COMMIT_SHA
      secrets:
        - name: github
# promotions:
# - name: Deploy
#   pipeline_file: deploy.yml
#   auto_promote:
#     when: "result = 'passed'"
execution_time_limit:
  minutes: 30
