version: v1.0
name: Deploy to production
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Deploy
    skip:
      when: "branch != 'prod'"
    task:
      jobs:
        - name: to VM
          commands:
            - gcloud compute ssh instance-2 --project united-watch-268115 --zone us-central1-a --ssh-key-file=google_compute_engine --command='cd FullStackFit && docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$PWD:$PWD" -w="$PWD" docker/compose:1.24.0  -f docker-compose-run-latest.yml pull && docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$PWD:$PWD" -w="$PWD" docker/compose:1.24.0  -f docker-compose-run-latest.yml up -d'
      prologue:
        commands:
          - gcloud auth activate-service-account --key-file=.secrets.gcp.json
          - chmod 600 google_compute_engine
          - chmod 600 google_compute_engine.pub
      secrets:
        - name: google-cloud-stg
promotions:
- name: Test prod
  pipeline_file: test-prod.yml
  auto_promote:
    when: "result = 'passed'"