name: Open pull request
on: push
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        pr_title: "Pulling ${{ github.ref }} into master"
        pr_label: "auto-pr"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_body: ":crown: *An automated PR*"  # Full markdown support, requires pr_title to be set