name: Open Pull Request
on: push
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        pr_title: "Pulling ${{ github.ref }} into master"
        pr_label: "auto-pr"
        github_token: ${{ secrets.GITHUB_TOKEN }}

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
    
#     - name: On my_custom_webhook do ABC...
#       run: |
#         echo "Hello From my_custom_webhook...doing ABC"